version: '3'
services:

  pgadmin:
    image: dpage/pgadmin4

    # Expose the web UI on localhost port 8080
    ports:
      - '8081:80'
    network_mode: bridge

    # Link this container to the postgres container with hostname 'postgres'
    external_links:
      - postgres:postgres

    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@example.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
