version: '3'
services:

  postgres:
    image: postgres:12.4-alpine

    # Expose the default Postgres port on localhost
    ports:
      - '5431:5432'
    network_mode: 'bridge'
    container_name: 'postgres'

    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'pgpass'
      POSTGRES_DB: 'milestone3'

    # Copy files from dbinit into the image so that they will be run on boot
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./saved_models:/var/lib/postgresql/data
 
  pgadmin:
    image: dpage/pgadmin4

    # Expose the web UI on localhost port 8080
    ports:
      - '8086:80'
    network_mode: bridge
    container_name: 'pgadmin'

    # Link this container to the postgres container with hostname 'postgres'
    external_links:
      - postgres:postgres

    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@example.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
      
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
    
      


